/*! \file */
/*******************************************
 *                                         *
 *  File auto-generated by `::safer_ffi`.  *
 *                                         *
 *  Do not manually edit this file.        *
 *                                         *
 *******************************************/

#ifndef __RUST_BFES__
#define __RUST_BFES__

#ifdef __cplusplus
extern "C" {
#endif


#include <stddef.h>
#include <stdint.h>

void bfes_new_index (
    int8_t const * name);

size_t bfes_add (
    int8_t const * name,
    float const * features,
    size_t dimension);

typedef struct SearchResult {

    size_t index;

    float score;

} SearchResult_t;

/** \brief
 *  Same as [`Vec<T>`][`rust::Vec`], but with guaranteed `#[repr(C)]` layout
 */
typedef struct Vec_SearchResult {

    SearchResult_t * ptr;

    size_t len;

    size_t cap;

} Vec_SearchResult_t;

Vec_SearchResult_t bfes_search (
    int8_t const * name,
    size_t k,
    float const * features,
    size_t dimension);

/** \brief
 *  Same as [`Vec<T>`][`rust::Vec`], but with guaranteed `#[repr(C)]` layout
 */
typedef struct Vec_float {

    float * ptr;

    size_t len;

    size_t cap;

} Vec_float_t;

Vec_float_t bfes_parse_embedding (
    int8_t const * embedding_string);

/** \brief
 *  Same as [`Vec<T>`][`rust::Vec`], but with guaranteed `#[repr(C)]` layout
 */
typedef struct Vec_Vec_float {

    Vec_float_t * ptr;

    size_t len;

    size_t cap;

} Vec_Vec_float_t;

Vec_Vec_float_t bfes_parse_embeddings (
    int8_t const * const * embedding_strings,
    ssize_t num);


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* __RUST_BFES__ */
